name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      uses: php-actions/composer@v6
      with:
        php_version: "8.1"
    - name: Install dependencies
      run: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
           
        
